import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import clsx from "clsx";
import SearchInput from "@/components/search-input/search-input";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(inter.className)}>
        <header className={styles.header}>
          <div className={styles.title}>
            <h1>
              <Link href="/posts">Posts</Link>
            </h1>
            <SearchInput placeholder="Search by author" searchParamName="q" />
          </div>
        </header>
        <main className={styles.main}>{children}</main>
      </body>
    </html>
  );
}
